require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DispatchesController do

  # This should return the minimal set of attributes required to create a valid
  # Dispatch. As you add validations to Dispatch, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all dispatches as @dispatches" do
      dispatch = Dispatch.create! valid_attributes
      get :index
      assigns(:dispatches).should eq([dispatch])
    end
  end

  describe "GET show" do
    it "assigns the requested dispatch as @dispatch" do
      dispatch = Dispatch.create! valid_attributes
      get :show, :id => dispatch.id.to_s
      assigns(:dispatch).should eq(dispatch)
    end
  end

  describe "GET new" do
    it "assigns a new dispatch as @dispatch" do
      get :new
      assigns(:dispatch).should be_a_new(Dispatch)
    end
  end

  describe "GET edit" do
    it "assigns the requested dispatch as @dispatch" do
      dispatch = Dispatch.create! valid_attributes
      get :edit, :id => dispatch.id.to_s
      assigns(:dispatch).should eq(dispatch)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dispatch" do
        expect {
          post :create, :dispatch => valid_attributes
        }.to change(Dispatch, :count).by(1)
      end

      it "assigns a newly created dispatch as @dispatch" do
        post :create, :dispatch => valid_attributes
        assigns(:dispatch).should be_a(Dispatch)
        assigns(:dispatch).should be_persisted
      end

      it "redirects to the created dispatch" do
        post :create, :dispatch => valid_attributes
        response.should redirect_to(Dispatch.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dispatch as @dispatch" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dispatch.any_instance.stub(:save).and_return(false)
        post :create, :dispatch => {}
        assigns(:dispatch).should be_a_new(Dispatch)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dispatch.any_instance.stub(:save).and_return(false)
        post :create, :dispatch => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dispatch" do
        dispatch = Dispatch.create! valid_attributes
        # Assuming there are no other dispatches in the database, this
        # specifies that the Dispatch created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dispatch.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => dispatch.id, :dispatch => {'these' => 'params'}
      end

      it "assigns the requested dispatch as @dispatch" do
        dispatch = Dispatch.create! valid_attributes
        put :update, :id => dispatch.id, :dispatch => valid_attributes
        assigns(:dispatch).should eq(dispatch)
      end

      it "redirects to the dispatch" do
        dispatch = Dispatch.create! valid_attributes
        put :update, :id => dispatch.id, :dispatch => valid_attributes
        response.should redirect_to(dispatch)
      end
    end

    describe "with invalid params" do
      it "assigns the dispatch as @dispatch" do
        dispatch = Dispatch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dispatch.any_instance.stub(:save).and_return(false)
        put :update, :id => dispatch.id.to_s, :dispatch => {}
        assigns(:dispatch).should eq(dispatch)
      end

      it "re-renders the 'edit' template" do
        dispatch = Dispatch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dispatch.any_instance.stub(:save).and_return(false)
        put :update, :id => dispatch.id.to_s, :dispatch => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dispatch" do
      dispatch = Dispatch.create! valid_attributes
      expect {
        delete :destroy, :id => dispatch.id.to_s
      }.to change(Dispatch, :count).by(-1)
    end

    it "redirects to the dispatches list" do
      dispatch = Dispatch.create! valid_attributes
      delete :destroy, :id => dispatch.id.to_s
      response.should redirect_to(dispatches_url)
    end
  end

end
