require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PcrsController do

  # This should return the minimal set of attributes required to create a valid
  # Pcr. As you add validations to Pcr, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all pcrs as @pcrs" do
      pcr = Pcr.create! valid_attributes
      get :index
      assigns(:pcrs).should eq([pcr])
    end
  end

  describe "GET show" do
    it "assigns the requested pcr as @pcr" do
      pcr = Pcr.create! valid_attributes
      get :show, :id => pcr.id.to_s
      assigns(:pcr).should eq(pcr)
    end
  end

  describe "GET new" do
    it "assigns a new pcr as @pcr" do
      get :new
      assigns(:pcr).should be_a_new(Pcr)
    end
  end

  describe "GET edit" do
    it "assigns the requested pcr as @pcr" do
      pcr = Pcr.create! valid_attributes
      get :edit, :id => pcr.id.to_s
      assigns(:pcr).should eq(pcr)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pcr" do
        expect {
          post :create, :pcr => valid_attributes
        }.to change(Pcr, :count).by(1)
      end

      it "assigns a newly created pcr as @pcr" do
        post :create, :pcr => valid_attributes
        assigns(:pcr).should be_a(Pcr)
        assigns(:pcr).should be_persisted
      end

      it "redirects to the created pcr" do
        post :create, :pcr => valid_attributes
        response.should redirect_to(Pcr.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pcr as @pcr" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pcr.any_instance.stub(:save).and_return(false)
        post :create, :pcr => {}
        assigns(:pcr).should be_a_new(Pcr)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pcr.any_instance.stub(:save).and_return(false)
        post :create, :pcr => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pcr" do
        pcr = Pcr.create! valid_attributes
        # Assuming there are no other pcrs in the database, this
        # specifies that the Pcr created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pcr.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => pcr.id, :pcr => {'these' => 'params'}
      end

      it "assigns the requested pcr as @pcr" do
        pcr = Pcr.create! valid_attributes
        put :update, :id => pcr.id, :pcr => valid_attributes
        assigns(:pcr).should eq(pcr)
      end

      it "redirects to the pcr" do
        pcr = Pcr.create! valid_attributes
        put :update, :id => pcr.id, :pcr => valid_attributes
        response.should redirect_to(pcr)
      end
    end

    describe "with invalid params" do
      it "assigns the pcr as @pcr" do
        pcr = Pcr.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pcr.any_instance.stub(:save).and_return(false)
        put :update, :id => pcr.id.to_s, :pcr => {}
        assigns(:pcr).should eq(pcr)
      end

      it "re-renders the 'edit' template" do
        pcr = Pcr.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pcr.any_instance.stub(:save).and_return(false)
        put :update, :id => pcr.id.to_s, :pcr => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pcr" do
      pcr = Pcr.create! valid_attributes
      expect {
        delete :destroy, :id => pcr.id.to_s
      }.to change(Pcr, :count).by(-1)
    end

    it "redirects to the pcrs list" do
      pcr = Pcr.create! valid_attributes
      delete :destroy, :id => pcr.id.to_s
      response.should redirect_to(pcrs_url)
    end
  end

end
